# Generated by Django 5.1.2 on 2024-11-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshpaz', '0004_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('position', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='comments/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='oshpaz.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oshpaz.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthyLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retsepts', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='')),
                ('categores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthylifes', to='oshpaz.category')),
            ],
        ),
        migrations.CreateModel(
            name='Myerrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('my_life', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('should_be_done', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myerrors', to='oshpaz.comment')),
                ('users_like', models.ManyToManyField(blank=True, related_name='my_error_liked', to='oshpaz.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalprescriptions', to='oshpaz.comment')),
                ('users_like', models.ManyToManyField(blank=True, db_table='users_like', related_name='likes', to='oshpaz.user')),
            ],
        ),
    ]
